---
abstract: 'Install L<KiokuDB> and related modules.'
author:
  - 'Yuval Kogman'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-KiokuDB
no_index:
  directory:
    - inc
    - t
requires:
  BerkeleyDB::Manager: 0
  JSON::XS: 0
  KiokuDB: 0
  KiokuDB::Backend::DBI: 0
  MooseX::Storage: 0
  Test::use::ok: 0
  YAML::XS: 0
  perl: 5.8.0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.07
